service: RossumCustomSkill
provider:
  name: aws
  runtime: nodejs8.10  
  region: us-east-1

functions:
  index:
    handler: index.handler
    name: RossumCustomSkill
    runtime: nodejs8.10
    timeout: 120
    events:
      - http:
          method: POST
          path: RossumCustomSkill
          cors: true