service: RossumCustomSkill
provider:
  name: aws
  runtime: nodejs8.10  
  region: us-east-1

functions:
  index:
    handler: index.handler
    name: RossumCustomSkill
    runtime: nodejs8.10
    timeout: 120
    events:
      - http:
          method: POST
          path: RossumCustomSkill
          cors: true
    environment:
      BOX_API_ENDPOINT: 'https://api.box.com/2.0'
      BOX_CLIENT_ID: YOUR_BOX_CLIENT_ID
      BOX_CLIENT_SECRET: YOUR_BOX_SECRET_KEY
      ROSSUM_SECRET_KEY: YOUR_ROSSUM_SECRET_KEY
